name: Docs

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write    # for deploy job
  id-token: write # for deploy job

jobs:
  build:
    name: Build docs (fast on PR)
    runs-on: ubuntu-latest
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      PYTHONUNBUFFERED: 1
      DOCS_FAST: ${{ github.event_name == 'pull_request' && '1' || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('docs/requirements.txt') }}

      - name: Install doc requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build HTML (strict)
        run: |
          sphinx-build -n -W -b html docs docs/_build/html

      - name: Run doctest
        run: |
          sphinx-build -n -W -b doctest docs docs/_build/doctest

      - name: Link check (tolerant)
        run: |
          # Avoid flaky anchors and reduce noise
          sphinx-build -b linkcheck -D linkcheck_anchors=false -D linkcheck_workers=5 \
            docs docs/_build/linkcheck

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build/html

  deploy:
    # Manual dispatch or push to main; requires Pages to be enabled in repo settings
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-html
          path: ./site

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

