name: Documentation Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'src/**'
      - '.github/workflows/docs-deploy.yml'
  workflow_dispatch:

permissions: {}  # default: none

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build HTML
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('docs/requirements*.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-
      - run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
      - run: sphinx-build -n -b html docs docs/_site
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_site

  deploy:
    name: Deploy to Pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
      - run: echo "::notice::Documentation deployed to ${{ steps.deployment.outputs.page_url }}"