name: tests
on:
  pull_request:
  push:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/src
      MPLBACKEND: Agg
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: python -m pip install -U pip
      - run: pip install -r requirements.txt || true
      - run: pip install pytest "pydantic>=2.5" pydantic-settings python-dotenv PyYAML

      - name: Show Python info
        run: |
          python --version
          python -c "import sys,os; print('PYTHONPATH:', os.environ.get('PYTHONPATH')); print('sys.path head:', sys.path[:3])"
          python -c "import importlib; m=importlib.import_module('src.config'); print('Loaded src.config OK:', bool(m))"

      - run: pytest -q
